export enum ServiceNames {
  AdminApi = 'adminapi',
  ApiGateway = 'api-gateway',
  Envoy = 'envoy',
  Functions = 'functions',
  Gotrue = 'gotrue',
  Kong = 'kong',
  Pgbouncer = 'pgbouncer',
  Pgsodium = 'pgsodium',
  Postgresql = 'postgresql',
  Postgrest = 'postgrest',
  Realtime = 'realtime',
  Storage = 'storage',
  Walg = 'walg',
  AutoShutdown = 'autoshutdown',
}

export const DEFAULT_REALTIME_SLOT_NAME_WITH_WALRUS = 'realtime_rls'

export enum PermissionAction {
  ANALYTICS_ADMIN_READ = 'analytics:Admin:Read',
  ANALYTICS_ADMIN_WRITE = 'analytics:Admin:Write',
  ANALYTICS_READ = 'analytics:Read',
  ANALYTICS_WRITE = 'analytics:Write',
  AUTH_EXECUTE = 'auth:Execute',
  BILLING_READ = 'billing:Read',
  BILLING_WRITE = 'billing:Write',
  CREATE = 'write:Create',
  DELETE = 'write:Delete',
  FUNCTIONS_READ = 'functions:Read',
  FUNCTIONS_WRITE = 'functions:Write',
  INFRA_EXECUTE = 'infra:Execute',
  READ = 'read:Read',
  SECRETS_READ = 'secrets:Read',
  SECRETS_WRITE = 'secrets:Write',
  SQL_SELECT = 'sql:Read:Select',
  SQL_DELETE = 'sql:Write:Delete',
  SQL_INSERT = 'sql:Write:Insert',
  SQL_UPDATE = 'sql:Write:Update',
  STORAGE_ADMIN_READ = 'storage:Admin:Read',
  STORAGE_ADMIN_WRITE = 'storage:Admin:Write',
  STORAGE_READ = 'storage:Read',
  STORAGE_WRITE = 'storage:Write',
  REALTIME_ADMIN_READ = 'realtime:Admin:Read',
  REALTIME_ADMIN_WRITE = 'realtime:Admin:Write',
  REPLICATION_ADMIN_READ = 'replication:Admin:Read',
  REPLICATION_ADMIN_WRITE = 'replication:Admin:Write',
  TENANT_SQL_ADMIN_READ = 'tenant:Sql:Admin:Read',
  TENANT_SQL_ADMIN_WRITE = 'tenant:Sql:Admin:Write',
  TENANT_SQL_CREATE_TABLE = 'tenant:Sql:CreateTable',
  TENANT_SQL_DELETE = 'tenant:Sql:Write:Delete',
  TENANT_SQL_INSERT = 'tenant:Sql:Write:Insert',
  TENANT_SQL_QUERY = 'tenant:Sql:Query',
  TENANT_SQL_SELECT = 'tenant:Sql:Read:Select',
  TENANT_SQL_UPDATE = 'tenant:Sql:Write:Update',
  UPDATE = 'write:Update',
}

export enum OAuthScope {
  ANALYTICS_READ = 'analytics:read',
  ANALYTICS_WRITE = 'analytics:write',
  AUTH_READ = 'auth:read',
  AUTH_WRITE = 'auth:write',
  DATABASE_READ = 'database:read',
  DATABASE_WRITE = 'database:write',
  DOMAINS_READ = 'domains:read',
  DOMAINS_WRITE = 'domains:write',
  EDGE_FUNCTIONS_READ = 'edge_functions:read',
  EDGE_FUNCTIONS_WRITE = 'edge_functions:write',
  ENVIRONMENT_READ = 'environment:read',
  ENVIRONMENT_WRITE = 'environment:write',
  ORGANIZATIONS_READ = 'organizations:read',
  ORGANIZATIONS_WRITE = 'organizations:write',
  PROJECTS_READ = 'projects:read',
  PROJECTS_WRITE = 'projects:write',
  REST_READ = 'rest:read',
  REST_WRITE = 'rest:write',
  SECRETS_READ = 'secrets:read',
  SECRETS_WRITE = 'secrets:write',
  STORAGE_READ = 'storage:read',
  STORAGE_WRITE = 'storage:write',
}

export enum SupportCategories {
  PROBLEM = 'Problem',
  DASHBOARD_BUG = 'Dashboard_bug',
  DATABASE_UNRESPONSIVE = 'Database_unresponsive',
  PERFORMANCE_ISSUES = 'Performance',
  SALES_ENQUIRY = 'Sales',
  BILLING = 'Billing',
  REFUND = 'Refund',
  ABUSE = 'Abuse',
  LOGIN_ISSUES = 'Login_issues',
  ACCOUNT_DELETION = 'Account_deletion',
}
