name: Run CI checks

on:
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 4

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: Run eslint
        run: |
          npm ci
          npm run lint
